$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$headerPath = Join-Path $root "ui_font_time_digits.h"
$cppPath = Join-Path $root "ui_font_time_digits.cpp"

$fontFamilyName = "Bahnschrift"
$fontStyle = [System.Drawing.FontStyle]::Regular
$emSize = 120
$boxH = 96
$lineHeight = 100
$baseLine = 4
$padX = 2
$glyphs = @(" ", "-", ":", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9")

$family = New-Object System.Drawing.FontFamily($fontFamilyName)
$format = [System.Drawing.StringFormat]::GenericTypographic
$format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoClip

$records = @()
$bitmapBytes = New-Object System.Collections.Generic.List[byte]

foreach ($glyph in $glyphs) {
  if ($glyph -eq " ") {
    $records += [pscustomobject]@{
      Code = [int][char]$glyph
      Index = 0
      Adv = 20
      W = 0
      H = 0
      OfsX = 0
      OfsY = 0
      Stride = 0
    }
    continue
  }

  $path = New-Object System.Drawing.Drawing2D.GraphicsPath
  $path.FillMode = [System.Drawing.Drawing2D.FillMode]::Winding
  $path.AddString($glyph, $family, [int]$fontStyle, $emSize, [System.Drawing.PointF]::new(0, 0), $format)
  $bounds = $path.GetBounds()
  $boxW = [Math]::Ceiling($bounds.Width) + ($padX * 2)
  $bmp = New-Object System.Drawing.Bitmap($boxW, $boxH, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.Clear([System.Drawing.Color]::Transparent)
  $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

  $matrix = New-Object System.Drawing.Drawing2D.Matrix
  $matrix.Translate(($padX - $bounds.X), ((($boxH - $bounds.Height) / 2.0) - $bounds.Y))
  $path.Transform($matrix)
  $brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
  $g.FillPath($brush, $path)

  $startIndex = $bitmapBytes.Count
  for ($y = 0; $y -lt $boxH; $y++) {
    for ($x = 0; $x -lt $boxW; $x++) {
      $bitmapBytes.Add($bmp.GetPixel($x, $y).A)
    }
  }

  $extraAdvance = if ($glyph -eq ":") { 2 } elseif ($glyph -eq "-") { 6 } else { 4 }
  $records += [pscustomobject]@{
    Code = [int][char]$glyph
    Index = $startIndex
    Adv = $boxW + $extraAdvance
    W = $boxW
    H = $boxH
    OfsX = 0
    OfsY = 0
    Stride = $boxW
  }

  $brush.Dispose()
  $matrix.Dispose()
  $g.Dispose()
  $bmp.Dispose()
  $path.Dispose()
}

$family.Dispose()
$format.Dispose()

function Format-ByteArray([byte[]]$bytes) {
  $lines = New-Object System.Collections.Generic.List[string]
  for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $end = [Math]::Min($i + 15, $bytes.Length - 1)
    $items = for ($j = $i; $j -le $end; $j++) { "0x{0:x2}" -f $bytes[$j] }
    $lines.Add("  " + ($items -join ", ") + ",")
  }
  return $lines -join "`r`n"
}

$bitmapText = Format-ByteArray $bitmapBytes.ToArray()
$recordLines = foreach ($record in $records) {
  "  {{ 0x{0:x4}, {1}, {2}, {3}, {4}, {5}, {6}, {7} }}," -f $record.Code, $record.Index, $record.Adv, $record.W, $record.H, $record.OfsX, $record.OfsY, $record.Stride
}
$recordText = $recordLines -join "`r`n"

$header = @"
#ifndef UI_FONT_TIME_DIGITS_H
#define UI_FONT_TIME_DIGITS_H

#include <lvgl.h>

extern const lv_font_t ui_font_time_digits_96;

#endif
"@

$cpp = @"
// Generated by tools/generate_time_font.ps1 from Windows Bahnschrift.
#define LV_CONF_INCLUDE_SIMPLE
#include <lvgl.h>
#include <stdint.h>
#include <string.h>

#include "ui_font_time_digits.h"

namespace {

struct TimeGlyph {
  uint32_t codepoint;
  uint32_t bitmapIndex;
  uint16_t advW;
  uint16_t boxW;
  uint16_t boxH;
  int16_t ofsX;
  int16_t ofsY;
  uint16_t stride;
};

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyphBitmap[] = {
$bitmapText
};

static const TimeGlyph glyphs[] = {
$recordText
};

const TimeGlyph* findGlyph(uint32_t letter) {
  for (size_t i = 0; i < sizeof(glyphs) / sizeof(glyphs[0]); i++) {
    if (glyphs[i].codepoint == letter) {
      return &glyphs[i];
    }
  }
  return nullptr;
}

bool getGlyphDsc(const lv_font_t*, lv_font_glyph_dsc_t* dsc, uint32_t letter, uint32_t) {
  if (dsc == nullptr) {
    return false;
  }

  const TimeGlyph* glyph = findGlyph(letter);
  if (glyph == nullptr) {
    return false;
  }

  memset(dsc, 0, sizeof(*dsc));
  dsc->adv_w = glyph->advW;
  dsc->box_w = glyph->boxW;
  dsc->box_h = glyph->boxH;
  dsc->ofs_x = glyph->ofsX;
  dsc->ofs_y = glyph->ofsY;
  dsc->stride = glyph->stride;
  dsc->format = LV_FONT_GLYPH_FORMAT_A8;
  dsc->gid.index = static_cast<uint32_t>(glyph - glyphs);
  return true;
}

const void* getGlyphBitmap(lv_font_glyph_dsc_t* dsc, lv_draw_buf_t*) {
  if (dsc == nullptr || dsc->gid.index >= sizeof(glyphs) / sizeof(glyphs[0])) {
    return nullptr;
  }

  const TimeGlyph& glyph = glyphs[dsc->gid.index];
  return glyphBitmap + glyph.bitmapIndex;
}

}  // namespace

const lv_font_t ui_font_time_digits_96 = {
  getGlyphDsc,
  getGlyphBitmap,
  nullptr,
  $lineHeight,
  $baseLine,
  LV_FONT_SUBPX_NONE,
  LV_FONT_KERNING_NONE,
  1,
  -4,
  2,
  nullptr,
  nullptr,
  nullptr
};
"@

Set-Content -Path $headerPath -Value $header -Encoding ASCII
Set-Content -Path $cppPath -Value $cpp -Encoding ASCII
