#!/usr/bin/env python3
"""
SVG -> LVGL 9 image converter with proper alpha handling.

Rasters an SVG in memory (no PNG file on disk) using CairoSVG, then writes
a C file with an `lv_image_dsc_t` in RGB565A8 (default) or ARGB8888 format.
Transparent SVG backgrounds stay transparent — no manual editing of the
generated C file needed.

Dependencies:
    pip install resvg-py pillow      # recommended on Windows (no native libs)
    # or
    pip install cairosvg pillow      # needs libcairo-2.dll on Windows

Usage:
    python svg2lvgl.py path/to/icon.svg                         # single file
    python svg2lvgl.py assets/icons -o src/ui_assets             # whole dir
    python svg2lvgl.py icon.svg --format argb8888 --size 64x64
    python svg2lvgl.py assets/icons -o out --prefix icon_ --header ui_assets.h

The C identifier is derived from the filename: dashes -> underscores,
optional prefix added. So `weather-clear.svg` with `--prefix icon_`
becomes `icon_weather_clear` (symbol) and `icon_weather_clear.c` (file).
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

_BACKEND = None
try:
    import resvg_py  # pure-Rust, no native lib needed
    _BACKEND = "resvg"
except ImportError:
    try:
        import cairosvg
        _BACKEND = "cairosvg"
    except ImportError:
        sys.exit("Missing dependency: pip install resvg-py pillow  (or cairosvg)")

try:
    from PIL import Image
except ImportError:
    sys.exit("Missing dependency: pip install pillow")


FORMATS = {"rgb565a8", "argb8888"}


def sanitize_identifier(stem: str, prefix: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z]+", "_", stem).strip("_").lower()
    if name and name[0].isdigit():
        name = "_" + name
    return f"{prefix}{name}" if prefix else name


def parse_size(s: str | None) -> tuple[int, int] | None:
    if not s:
        return None
    m = re.fullmatch(r"\s*(\d+)\s*[xX]\s*(\d+)\s*", s)
    if not m:
        raise argparse.ArgumentTypeError(f"--size must be WxH, got {s!r}")
    return int(m.group(1)), int(m.group(2))


def render_svg(svg_path: Path, size: tuple[int, int] | None) -> Image.Image:
    if _BACKEND == "resvg":
        kwargs = {"svg_path": str(svg_path)}
        if size:
            kwargs["width"], kwargs["height"] = size
        png_bytes = resvg_py.svg_to_bytes(**kwargs)
        if isinstance(png_bytes, list):
            png_bytes = bytes(png_bytes)
    else:
        kwargs = {"url": str(svg_path)}
        if size:
            kwargs["output_width"], kwargs["output_height"] = size
        png_bytes = cairosvg.svg2png(**kwargs)
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    return img


def to_rgb565a8(img: Image.Image) -> tuple[bytes, int]:
    """LVGL 9 RGB565A8: planar — w*h*2 bytes RGB565 (LE), then w*h*1 bytes A."""
    w, h = img.size
    rgb_buf = bytearray(w * h * 2)
    alpha_buf = bytearray(w * h)
    px = img.load()
    i = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            rgb_buf[i * 2] = v & 0xFF
            rgb_buf[i * 2 + 1] = (v >> 8) & 0xFF
            alpha_buf[i] = a
            i += 1
    return bytes(rgb_buf) + bytes(alpha_buf), w * h * 3


def to_argb8888(img: Image.Image) -> tuple[bytes, int]:
    """LVGL stores ARGB8888 as little-endian B,G,R,A per pixel."""
    w, h = img.size
    out = bytearray(w * h * 4)
    px = img.load()
    i = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            out[i] = b
            out[i + 1] = g
            out[i + 2] = r
            out[i + 3] = a
            i += 4
    return bytes(out), w * h * 4


def format_bytes(data: bytes, per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


C_TEMPLATE = """\
/*
 * Auto-generated by tools/svg2lvgl.py — do not edit by hand.
 * Source: {source}
 * Size:   {w}x{h}
 * Format: {cf_human}
 */

#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_{upper}
    #define LV_ATTRIBUTE_IMAGE_{upper}
#endif

static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST
    LV_ATTRIBUTE_IMAGE_{upper} uint8_t {sym}_map[] = {{
{body}
}};

const lv_image_dsc_t {sym} = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf    = {cf_macro},
    .header.w     = {w},
    .header.h     = {h},
    .header.stride = {stride},
    .data_size    = {data_size},
    .data         = {sym}_map,
}};
"""


def write_c_file(
    out_path: Path,
    sym: str,
    source: Path,
    w: int,
    h: int,
    fmt: str,
    data: bytes,
    data_size: int,
) -> None:
    if fmt == "rgb565a8":
        cf_macro = "LV_COLOR_FORMAT_RGB565A8"
        cf_human = "RGB565A8 (planar: RGB565 LE + A8)"
        stride = w * 2
    else:
        cf_macro = "LV_COLOR_FORMAT_ARGB8888"
        cf_human = "ARGB8888 (LE: B,G,R,A)"
        stride = w * 4

    c_src = C_TEMPLATE.format(
        source=source.as_posix(),
        w=w,
        h=h,
        cf_human=cf_human,
        cf_macro=cf_macro,
        upper=sym.upper(),
        sym=sym,
        stride=stride,
        data_size=data_size,
        body=format_bytes(data),
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(c_src, encoding="utf-8")


def convert_one(
    svg: Path,
    out_dir: Path,
    fmt: str,
    size: tuple[int, int] | None,
    prefix: str,
) -> tuple[str, int, int]:
    img = render_svg(svg, size)
    w, h = img.size
    if fmt == "rgb565a8":
        data, data_size = to_rgb565a8(img)
    else:
        data, data_size = to_argb8888(img)
    sym = sanitize_identifier(svg.stem, prefix)
    write_c_file(out_dir / f"{sym}.c", sym, svg, w, h, fmt, data, data_size)
    return sym, w, h


def write_header(header_path: Path, symbols: list[str]) -> None:
    lines = [
        "#pragma once",
        "",
        "#include <lvgl.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for sym in sorted(symbols):
        lines.append(f"LV_IMAGE_DECLARE({sym});")
    lines += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input", type=Path, help="SVG file or directory of SVGs")
    p.add_argument("-o", "--out", type=Path, default=None, help="Output directory (default: alongside input)")
    p.add_argument("--format", choices=sorted(FORMATS), default="rgb565a8", help="LVGL color format (default: rgb565a8)")
    p.add_argument("--size", type=parse_size, default=None, help="Force output size, e.g. 48x48")
    p.add_argument("--prefix", default="", help="Prefix for C identifiers, e.g. icon_")
    p.add_argument("--header", type=Path, default=None, help="Also write an aggregate header with LV_IMAGE_DECLARE lines")
    args = p.parse_args()

    if not args.input.exists():
        sys.exit(f"Input not found: {args.input}")

    if args.input.is_dir():
        svgs = sorted(args.input.glob("*.svg"))
        if not svgs:
            sys.exit(f"No .svg files in {args.input}")
        out_dir = args.out or args.input
    else:
        svgs = [args.input]
        out_dir = args.out or args.input.parent

    symbols: list[str] = []
    for svg in svgs:
        try:
            sym, w, h = convert_one(svg, out_dir, args.format, args.size, args.prefix)
        except Exception as e:
            print(f"  FAIL {svg.name}: {e}", file=sys.stderr)
            continue
        symbols.append(sym)
        print(f"  OK   {svg.name} -> {sym}.c ({w}x{h}, {args.format})")

    if args.header and symbols:
        write_header(args.header, symbols)
        print(f"  Wrote header {args.header} with {len(symbols)} declarations")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
